version: "3.7"
services:
  serv-front:
    image: myapp-front:latest
    networks:
      - overlay
    ports:
      - 8080:8080
  serv-api:
    build: myapp-api:latest
    deploy:
      restart: always # https://docs.docker.com/compose/compose-file/#deploy
    environment:
      - WHITELIST=http://localhost:8080
      - PORT=4500
      - DB_USER=admin
      - DB_PASSWORD=example
      - DB_NAME=DEFAULT_DB
      - DB_HOST=serv-db:27017
    networks:
      - overlay
    ports:
      - 4500:4500
    volumes:
      - pgsock
  serv-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=DEFAULT_DB
    networks:
      - overlay
    volumes:
      - "dbdata:/data/db"

networks:
  overlay:
    driver: overlay
volumes:
  dbdata:
